---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://liz-miller.github.io/queenflex"
title: "Queenflex"
canonifyurls: true
theme: "hugo-tranquilpeak-theme"
...